# Form implementation generated from reading ui file 'ui_gui_app.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gui_app(object):
    def setupUi(self, gui_app):
        gui_app.setObjectName("gui_app")
        gui_app.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=gui_app)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(gui_app)
        self.buttonBox.accepted.connect(gui_app.accept) # type: ignore
        self.buttonBox.rejected.connect(gui_app.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(gui_app)

    def retranslateUi(self, gui_app):
        _translate = QtCore.QCoreApplication.translate
        gui_app.setWindowTitle(_translate("gui_app", "Suchmaschine"))
